"""
Generate a solid red heart as an LVGL RGB565 C array for the 喵伴 Qixi easter
egg. The previous text-glyph '♥' rendered as a tofu box because the on-board
font lacks that glyph, so we use a real bitmap heart instead (not the old
animated GIF — just a single static red heart shape).

Usage:
    python gen_heart_red.py
Outputs main/heart_red.c and main/heart_red.h.
"""
import os
from PIL import Image, ImageDraw

OUT_DIR = os.path.join(os.path.dirname(__file__), "..", "main")
OUT_C = os.path.join(OUT_DIR, "heart_red.c")
OUT_H = os.path.join(OUT_DIR, "heart_red.h")

W, H = 26, 24
RED = (255, 40, 70)


def rgb565(r, g, b):
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)


def main():
    img = Image.new("RGB", (W, H), (0, 0, 0))
    d = ImageDraw.Draw(img)
    # Two top lobes + a bottom point form a heart.
    d.ellipse((1, 1, 14, 15), fill=RED)
    d.ellipse((12, 1, 25, 15), fill=RED)
    d.polygon([(1, 9), (25, 9), (13, 23)], fill=RED)

    px = img.load()
    buf = bytearray()
    for y in range(H):
        for x in range(W):
            r, g, b = px[x, y][:3]
            v = rgb565(r, g, b)
            buf += bytes([v & 0xFF, (v >> 8) & 0xFF])

    with open(OUT_H, "w", encoding="utf-8") as f:
        f.write("#pragma once\n")
        f.write("#include <stdint.h>\n\n")
        f.write("#define HEART_RED_W %d\n" % W)
        f.write("#define HEART_RED_H %d\n" % H)
        f.write("extern const uint8_t heart_red_data[HEART_RED_W * HEART_RED_H * 2];\n")

    with open(OUT_C, "w", encoding="utf-8") as f:
        f.write("/* Auto-generated by gen_heart_red.py (solid red heart) — do not edit. */\n")
        f.write('#include "heart_red.h"\n\n')
        f.write("const uint8_t heart_red_data[HEART_RED_W * HEART_RED_H * 2] = {\n")
        for i in range(0, len(buf), 12):
            f.write("  ")
            f.write("".join("0x%02x, " % b for b in buf[i:i + 12]))
            f.write("\n")
        f.write("};\n")
    print("OK red heart %dx%d RGB565 -> %s" % (W, H, OUT_C))


if __name__ == "__main__":
    main()
