"""
Generate a large artistic-calligraphy "七夕快乐" banner as an LVGL RGB565 C
array for the 喵伴 Qixi easter egg.

Uses the Windows artistic CJK font STXINGKA.TTF (华文行楷). Renders gold glyphs
with a soft red shadow on a black background, crops to content, fits within a
round 360px screen, and emits raw RGB565 (16-bit little-endian) bytes — exactly
the same pixel format the GIF converters use, so it can be shown with an
lv_image_dsc_t.

Usage:
    python gen_qixi_banner.py
Outputs main/qixi_banner.c and main/qixi_banner.h.
"""
import os
import sys
from PIL import Image, ImageDraw, ImageFont

FONT = r"C:\Windows\Fonts\STXINGKA.TTF"
TEXT = "七夕快乐"
OUT_DIR = os.path.join(os.path.dirname(__file__), "..", "main")
OUT_C = os.path.join(OUT_DIR, "qixi_banner.c")
OUT_H = os.path.join(OUT_DIR, "qixi_banner.h")

MAX_W = 330
MAX_H = 120
GOLD = (255, 210, 77)
SHADOW = (176, 44, 57)
FONT_PX = 130


def rgb565(r, g, b):
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)


def main():
    if not os.path.exists(FONT):
        print("FONT missing:", FONT)
        sys.exit(1)
    font = ImageFont.truetype(FONT, FONT_PX)

    # Measure text bbox to size the temp canvas.
    tmp = Image.new("RGB", (10, 10), (0, 0, 0))
    d = ImageDraw.Draw(tmp)
    bbox = d.textbbox((0, 0), TEXT, font=font)
    pad = 24
    w = bbox[2] - bbox[0] + pad * 2
    h = bbox[3] - bbox[1] + pad * 2
    img = Image.new("RGB", (w, h), (0, 0, 0))
    dr = ImageDraw.Draw(img)
    tx = pad - bbox[0]
    ty = pad - bbox[1]
    # red drop shadow
    dr.text((tx + 4, ty + 5), TEXT, font=font, fill=SHADOW)
    # gold glyphs
    dr.text((tx, ty), TEXT, font=font, fill=GOLD)

    # Crop to non-black content.
    bw = img.convert("L").point(lambda p: 255 if p > 8 else 0)
    crop = bw.getbbox()
    if crop:
        img = img.crop(crop)

    # Fit within MAX_W x MAX_H, preserving aspect.
    iw, ih = img.size
    scale = min(MAX_W / iw, MAX_H / ih, 1.0)
    nw, nh = max(1, int(iw * scale)), max(1, int(ih * scale))
    img = img.resize((nw, nh), Image.LANCZOS)

    px = img.load()
    buf = bytearray()
    for y in range(nh):
        for x in range(nw):
            r, g, b = px[x, y][:3]
            v = rgb565(r, g, b)
            buf += bytes([v & 0xFF, (v >> 8) & 0xFF])

    with open(OUT_H, "w", encoding="utf-8") as f:
        f.write("#pragma once\n")
        f.write("#include <stdint.h>\n\n")
        f.write(f"#define QIXI_BANNER_W {nw}\n")
        f.write(f"#define QIXI_BANNER_H {nh}\n")
        f.write(f"extern const uint8_t qixi_banner_data[QIXI_BANNER_W * QIXI_BANNER_H * 2];\n")

    with open(OUT_C, "w", encoding="utf-8") as f:
        f.write("/* Auto-generated by gen_qixi_banner.py (STXINGKA calligraphy) — do not edit. */\n")
        f.write('#include "qixi_banner.h"\n\n')
        f.write(f"const uint8_t qixi_banner_data[QIXI_BANNER_W * QIXI_BANNER_H * 2] = {{\n")
        for i in range(0, len(buf), 12):
            f.write("  ")
            f.write("".join("0x%02x, " % b for b in buf[i:i + 12]))
            f.write("\n")
        f.write("};\n")
    print(f"OK banner {nw}x{nh} RGB565 -> {OUT_C}")


if __name__ == "__main__":
    main()
